err
Command line: /Users/a1667917/mambaforge/envs/dnaapler/bin/python3.11 /Users/a1667917/Documents/dnaapler/tests/helpers/run_test.py output input
